### ISSUE TITLE
feature: Update CONTRIBUTING.md to Reflect Languages

### ISSUE THREAD

**Issue by robertcrockett** [rallyhealth/angular-yuzi#18]
## Feature Request

Proposed Change is to remove the reference to Lua and add the appropriate languages for this repository

Documentation Change Only

```diff
- *Lua*
+ #### Primary Language
+
+ *Typescript*
+
+ #### Additional Languages
+
+ - *Stylus*
+ - *HTML*
+ - *Javascript*
```

## Task List
_Put an `x` in the boxes that apply_

- [x] Describe the feature being requested
- [x] Describe a preferred solution
- [ ] Provide examples or related code if applicable

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_
- [x] Yes
- [ ] No
